### ISSUE TITLE
Can't build 0.3.0 works fine with 0.2.2

### ISSUE THREAD

**Issue by dimityrivanov** [jnschulze/flutter-webview-windows#261]
Hey guys,

I managed to move from 0.1.6 version to 0.2.2 installing the proper visual studio code sds and CMAKE file but when I try to move from 0.2.2 to 0.3.0 I get the following error while building:

```
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_windows_plugin.cc(209,22): error C2039: 'format': is not a member of 'std' [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_windows_plugin.cc(229,7): error C3861: 'format': identifier not found [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview.cc(432,27): error C2039: 'format': is not a member of 'std' [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview.cc(432,33): error C3861: 'format': identifier not found [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(179,12): error C2039: 'format': is not a member of 'std' [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(179,18): error C3861: 'format': identifier not found [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(181,12): error C2672: 'std::make_unique': no matching overloaded function found [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(183,55): error C2893: Failed to specialize function template 'std::unique_ptr<_Ty,std::default_delete<_Ty>> std::make_unique(_Types &&...)' [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(189,12): error C2039: 'format': is not a member of 'std' [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(189,18): error C3861: 'format': identifier not found [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(191,12): error C2672: 'std::make_unique': no matching overloaded function found [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\windows\flutter\ephemeral\.plugin_symlinks\webview_windows\windows\webview_bridge.cc(193,55): error C2893: Failed to specialize function template 'std::unique_ptr<_Ty,std::default_delete<_Ty>> std::make_unique(_Types &&...)' [C:\Users\dimit\OneDrive\Documents\GitHub\test\test_app\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
```

**Comment by lucasjinreal** [comment]
Same here.
