### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jayaganeshk** [jnschulze/flutter-webview-windows#239]
While Running facing below error.
Flutter verion: 3.7.5
Visual Studio: 2022

```C:/Users/Administrator/Documents/codecommit/url_host/build/windows/plugins/webview_windows/Debug/webview_windows_plugin.exp
[ +685 ms] std.ixx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void (__cdecl* std::_Raise_handler)(class
stdext::exception const &)" (__imp_?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA::<!std>) referenced in function "public: void    
__cdecl stdext::exception::_Raise(void)const " (?_Raise@exception@stdext@@QEBAXXZ::<!std>)
[C:\Users\Administrator\Documents\codecommit\url_host\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
```

**Comment by jayaganeshk** [comment]
i downgraded the version to 0.2.1. Seems to be working fine on 0.2.1 version.
@riccardo-lomazzi

**Comment by Darkmessage** [comment]
This seems to be a Visual Studio problem.
I built my app and it worked.
Changed nothing but upgraded Visual Studio to 17.6 and I got this error.
Also VS 17.6.1 and the 17.7 preview had this error.

As you said, downgrading this package to 0.2.1 worked.

So somehow 0.2.2 and VS 17.6 don't go along.
(I don't know what VS version I had prior to 17.6, so can't really say which version worked.)

**Comment by riccardo-lomazzi** [comment]
> Downgrading works in `Debug`, but not in `Release`.
> 
> `fatal error C1083: Cannot open include file: 'wil/com.h': No such file or directory [D:\Apps\exampleapp\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]`

I've managed to make it work. Here's what I did.
The problem lies in the fact that the `wil` library (`Windows Implementation Library`) is missing from the plugin compilation, for some reason.
You cannot add it to the built plugin project, as it deleted and recompiled everytime.
As you may know, the plugin's `Additional Include Directories` also look inside the project's `windows/flutter/ephemeral` folder, which is deleted after every `flutter clean`.
My solution was to modify the `CMakeLists.txt` file to copy the library in the `ephemeral` folder at every build.

So,

1. Download `Windows Implementation Library` by nuget ([link](https://www.nuget.org/packages/Microsoft.Windows.ImplementationLibrary/))
2. Install it with Visual Studio, and go to the `%userprofile%/.nuget/packages/microsoft.windows.implementationlibrary/1.0.220914.1/include` folder.
3. Copy the `wil` folder inside the project's `windows/runner/resources/`
4. Edit the `windows/flutter/CMakeLists.txt` by inserting the following lines.
```cmake
# TODO: Move the rest of this into files in ephemeral. See
# https://github.com/flutter/flutter/issues/57146.
set(WRAPPER_ROOT "${EPHEMERAL_DIR}/cpp_client_wrapper")

# INSERT THIS LINE HERE
file(COPY "${PROJECT_DIR}/windows/runner/resources/wil" DESTINATION "${EPHEMERAL_DIR}/")

# === Flutter Library ===
set(FLUTTER_LIBRARY "${EPHEMERAL_DIR}/flutter_windows.dll")
```

Hope it helps until the `0.2.2` version will work with a future VS2022 release.

**Comment by hyUrbanManager** [comment]
> While Running facing below error. Flutter verion: 3.7.5 Visual Studio: 2022
> 
> ```
> [ +685 ms] std.ixx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void (__cdecl* std::_Raise_handler)(class
> stdext::exception const &)" (__imp_?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA::<!std>) referenced in function "public: void    
> __cdecl stdext::exception::_Raise(void)const " (?_Raise@exception@stdext@@QEBAXXZ::<!std>)
> [C:\Users\Administrator\Documents\codecommit\url_host\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
> ```

version 0.2.2, change file CMakeLists.txt, line 77, 
target_compile_features(${PLUGIN_NAME} PUBLIC cxx_std_23)
to
target_compile_features(${PLUGIN_NAME} PUBLIC cxx_std_20)
can solve this problem

**Comment by mustafal** [comment]
> > While Running facing below error. Flutter verion: 3.7.5 Visual Studio: 2022
> > ```
> > [ +685 ms] std.ixx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void (__cdecl* std::_Raise_handler)(class
> > stdext::exception const &)" (__imp_?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA::<!std>) referenced in function "public: void    
> > __cdecl stdext::exception::_Raise(void)const " (?_Raise@exception@stdext@@QEBAXXZ::<!std>)
> > [C:\Users\Administrator\Documents\codecommit\url_host\build\windows\plugins\webview_windows\webview_windows_plugin.vcxproj]
> > ```
> 
> version 0.2.2, change file CMakeLists.txt, line 77, target_compile_features(${PLUGIN_NAME} PUBLIC cxx_std_23) to target_compile_features(${PLUGIN_NAME} PUBLIC cxx_std_20) can solve this problem

This worked for me...
Thanks a lot

**Comment by schmitzli** [comment]
VS 17.5.3 is a version where this was still working, but it might be caused by a bug fixed ;-)

**Comment by flutterdev-ravan** [comment]
When encountering the given error while running, with Flutter version 3.7.5 and Visual Studio 2022, modifying line 77 in the CMakeLists.txt file of version 0.2.2 can resolve the issue. Specifically, changing "target_compile_features(${PLUGIN_NAME} PUBLIC cxx_std_23)" to "target_compile_features(${PLUGIN_NAME} PUBLIC cxx_std_20)" provides a successful solution.

**Comment by zoenie123** [comment]
> 
I cannot find that particular CMakeLists.txt file, where is it located?

**Comment by hiepvip99** [comment]
> > 
> 
> Tôi không thể tìm thấy tệp cụ thể CMakeLists.txt đó, nó nằm ở đâu?

you search in C:\Users\Admin\AppData\Local\Pub\Cache\hosted\pub.dev\webview_windows-0.2.2\windows

**Comment by hyUrbanManager** [comment]
> 

https://github.com/jnschulze/flutter-webview-windows/blob/main/windows/CMakeLists.txt

**Comment by zoenie123** [comment]
Ok, that worked for me. When can we expect an update to the plugin?
